
# Some ground rules:
#   1. Prefer to relax a rule rather than disable it outright.
#   2. Handle one-off exceptions via an inline comment: rubocop:enable/disable <linter check name, ...>
#   3. Keep this file sorted A-Z

AllCops:
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 40
